### ISSUE TITLE
Order of labs

### ISSUE THREAD

**Issue by richie1982** [learn-co-curriculum/react-jsx#18]
In order to avoid confusion for students, this lab should be ordered before the "react-dynamic-components-lab." There are many syntactical necessities not covered prior to this that are essential for being able to pass the previous 'dynamic components' lab.

**Comment by maxwellbenton** [comment]
Hi @richie1982,

Thanks for reporting this issue. We're now aware of it and are tracking this and other ordering issues in a new issue [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3).

We are currently updating and restructuring the materials in this section and will add this to our internal work queue. We will be updating the order of lessons in the next phase of this process and will take this information into consideration in upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when this issue is resolved.

Thanks for contributing!
