### ISSUE TITLE
Should come before Dynamic Components Lab

### ISSUE THREAD

**Issue by lesliesage** [learn-co-curriculum/react-jsx#19]
The lab right before this ReadMe asks us to write some JSX if/then statements having never seen anything like it. I tried like 10 combinations of punctuation and stuff before just looking at the solution branch. Is this ReadMe supposed to come first?

**Comment by maxwellbenton** [comment]
Hi @lesliesage,

Thanks for reporting this issue. We're now aware of it and are tracking this and other ordering issues in a new issue [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3). 

We are currently updating and restructuring the materials in this section and will add this to our internal work queue.  We will be updating the order of lessons in the next phase of this process and will take this information into consideration in upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when this issue is resolved.

Thanks for contributing!
