### ISSUE TITLE
Order of information

### ISSUE THREAD

**Issue by PeteHanner** [learn-co-curriculum/react-jsx#20]
Possibly move this before the Dynamic Components readings and lab? This lab specifically states that if-else blocks don't work in JSX, while ternary operators do, which is explicitly needed to solved the Dynamic Components lab.

**Comment by maxwellbenton** [comment]
Hi @PeteHanner,

Thank you for providing this feedback. We've updated the in-person course track so that this lesson precedes the Dynamic Components readme and lab. Immersive students should see this change immediately on refresh of Learn. We're also tracking this order issue [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3) to ensure this change makes it to other student groups using Learn and will complete this reorder for all students in an upcoming update. 

Since this order issue is already being tracked and is resolved for immersive students, I'm going to close this issue.

Thank you for contributing!
