### ISSUE TITLE
"Imperative" JavaScript?

### ISSUE THREAD

**Issue by kjgenevieve** [learn-co-curriculum/react-jsx#21]
So far as I remember, we haven't covered imperative vs declarative programming, so saying that
> The JSX needs to be converted into regular, imperative Javascript

is more confusing than helpful. It's also not explained _why_ the previous code won't work, so as learners, we don't actually know what to avoid.

Later, the reading also says
> While JSX introduces some new rules we must follow, the benefit is that we can write code that is semantic and _declarative_.

So now I'm completely confused about imperative vs declarative, what they are, and which I should use in what circumstances.

**Comment by maxwellbenton** [comment]
Hi @kjgenevieve,

Thank you for spotting this and opening an issue. We've updated this lesson so that it introduces the terms `imperative` and `declarative` first and provides an example before going into detail on JSX. We've also clarified the sections you point out to help prevent confusion for future students.

We apologize for any confusion or frustration this lesson may have caused, but we appreciate you taking the time to provide this feedback and help ensure future students do not encounter the same issues you encountered.

Thank you for contributing!
